### ISSUE TITLE
Missing FS25_000_DevTools.zip

### ISSUE THREAD

**Issue by monsieurbab** [w33zl/FS25_DataDump#1]
Hello, I can't activate the mod in the mod manager because the FS25_000_DevTools mod is missing, but it seems to be private on your GitHub : https://github.com/w33zl/FS25_DevTools

![image](https://github.com/user-attachments/assets/de3a99fe-7ff8-4c27-9276-f67824c10c16)

**Comment by w33zl** [comment]
Hi, yes that is correct. I was a bit quick to publish the new DataDump before DevTools was ready to be publicly available. I have the DevTools as pending testing at Giants, and I would prefer to have their feedback before releasing it on GH. However, if I don't get any news within a few days I might publish DevTools here first. So, please have patience for a couple of days, or reach out to me on Facebook (https://www.facebook.com/w33zl) and we might sort something out.

**Comment by w33zl** [comment]
DevTools now released on ModHub: https://www.farming-simulator.com/mod.php?mod_id=303447&title=fs2025
